---
airflow_environment_name: "" # Override this value using inventory variable/external variable 
airflow_python_version: "" # Incase of empty, it will be dynamically calculated by role
airflow_home: "/home/ubuntu/airflow"
airflow_version: 2.2.4
airflow_web_port: 8080
airflow_setup_state: "present" #To uninstall set this value to "absent"

airflow_timezone: "EST"
airflow_database_type: "sqllite"

# Below variable needed when external database is used as airflow backend
airflow_database_name: "postgres"
airflow_database_port: "5432"
airflow_database_host: "localhost"
airflow_database_username: "postgres"
airflow_database_password: "admin"

airflow_default_users:
  - username: admin
    email: admin@gmail.com
    firstname: admin
    lastname: admin
    password: admin
