- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Upgrade pip to latest version
  pip:
    name: pip
    state: latest
    executable: pip3
